import { Product } from '@/types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    title: 'Emerald Green Wedding Lehenga',
    category: 'Lehengas',
    size: 'UK 10',
    condition: 'Like new',
    price: 450,
    images: ['/placeholder-product.jpg'],
    location: 'London',
    seller_id: 'mock-seller-1',
  },
  {
    id: '2',
    title: 'Red Kanjivaram Silk Saree',
    category: 'Sarees',
    size: 'One Size',
    condition: 'Good',
    price: 180,
    images: ['/placeholder-product.jpg'],
    location: 'Birmingham',
    seller_id: 'mock-seller-2',
  },
  {
    id: '3',
    title: 'Navy Blue Sherwani',
    category: 'Sherwanis',
    size: 'UK 40',
    condition: 'Like new',
    price: 320,
    images: ['/placeholder-product.jpg'],
    location: 'Manchester',
    seller_id: 'mock-seller-3',
  },
  {
    id: '4',
    title: 'Pink Embroidered Anarkali',
    category: 'Anarkali',
    size: 'UK 12',
    condition: 'New with tags',
    price: 280,
    images: ['/placeholder-product.jpg'],
    location: 'Leicester',
    seller_id: 'mock-seller-4',
  },
  {
    id: '5',
    title: 'Gold Reception Lehenga',
    category: 'Lehengas',
    size: 'UK 8',
    condition: 'Good',
    price: 380,
    images: ['/placeholder-product.jpg'],
    location: 'London',
    seller_id: 'mock-seller-5',
  },
  {
    id: '6',
    title: "Men's Ivory Kurta Set",
    category: 'Kurtas & Kurtis',
    size: 'UK 38',
    condition: 'Like new',
    price: 95,
    images: ['/placeholder-product.jpg'],
    location: 'Leeds',
    seller_id: 'mock-seller-6',
  },
  {
    id: '7',
    title: 'Maroon Banarasi Saree',
    category: 'Sarees',
    size: 'One Size',
    condition: 'Good',
    price: 160,
    images: ['/placeholder-product.jpg'],
    location: 'Bradford',
    seller_id: 'mock-seller-7',
  },
  {
    id: '8',
    title: 'Peach Designer Salwar Kameez',
    category: 'Salwar Kameez',
    size: 'UK 14',
    condition: 'Like new',
    price: 145,
    images: ['/placeholder-product.jpg'],
    location: 'Coventry',
    seller_id: 'mock-seller-8',
  },
];
